In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Bob"],
    "Age": [25, 30, np.nan, 28, 22, 30],
    "City": ["Pune", "Mumbai", "Delhi", np.nan, "Pune", "Mumbai"],
    "Salary": [50000, 60000, 55000, np.nan, 45000, 60000]
}

df = pd.DataFrame(data)

print(df)

      Name   Age    City   Salary
0    Alice  25.0    Pune  50000.0
1      Bob  30.0  Mumbai  60000.0
2  Charlie   NaN   Delhi  55000.0
3    David  28.0     NaN      NaN
4      Eva  22.0    Pune  45000.0
5      Bob  30.0  Mumbai  60000.0

In [2]:
#selecting Rows and colums

In [5]:
df["Name"]

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
5        Bob
Name: Name, dtype: str

In [6]:
df[["Name","Age"]]

      Name   Age
0    Alice  25.0
1      Bob  30.0
2  Charlie   NaN
3    David  28.0
4      Eva  22.0
5      Bob  30.0

In [7]:
df.iloc[0]

Name        Alice
Age          25.0
City         Pune
Salary    50000.0
Name: 0, dtype: object

In [9]:
df.iloc[0:3,0:1]

      Name
0    Alice
1      Bob
2  Charlie

In [12]:
df.head(2)

    Name   Age    City   Salary
0  Alice  25.0    Pune  50000.0
1    Bob  30.0  Mumbai  60000.0

In [15]:
df.iloc[:4]

      Name   Age    City   Salary
0    Alice  25.0    Pune  50000.0
1      Bob  30.0  Mumbai  60000.0
2  Charlie   NaN   Delhi  55000.0
3    David  28.0     NaN      NaN

In [16]:
df.loc[2:5,["Name","Age"]]

      Name   Age
2  Charlie   NaN
3    David  28.0
4      Eva  22.0
5      Bob  30.0

In [17]:
df["Age"] < 30

0     True
1    False
2    False
3     True
4     True
5    False
Name: Age, dtype: bool

In [18]:
df[df["City"] == "Mumbai"]

  Name   Age    City   Salary
1  Bob  30.0  Mumbai  60000.0
5  Bob  30.0  Mumbai  60000.0

In [19]:
df[df["Salary"] > 50000]

      Name   Age    City   Salary
1      Bob  30.0  Mumbai  60000.0
2  Charlie   NaN   Delhi  55000.0
5      Bob  30.0  Mumbai  60000.0

In [20]:
#employees from pune and delhi

df[df["City"].isin(["Pune","Delhi"])]

      Name   Age   City   Salary
0    Alice  25.0   Pune  50000.0
2  Charlie   NaN  Delhi  55000.0
4      Eva  22.0   Pune  45000.0

In [21]:
df.sort_values("Salary")

      Name   Age    City   Salary
4      Eva  22.0    Pune  45000.0
0    Alice  25.0    Pune  50000.0
2  Charlie   NaN   Delhi  55000.0
1      Bob  30.0  Mumbai  60000.0
5      Bob  30.0  Mumbai  60000.0
3    David  28.0     NaN      NaN

In [22]:
df.sort_values("Age", ascending=False)

      Name   Age    City   Salary
1      Bob  30.0  Mumbai  60000.0
5      Bob  30.0  Mumbai  60000.0
3    David  28.0     NaN      NaN
0    Alice  25.0    Pune  50000.0
4      Eva  22.0    Pune  45000.0
2  Charlie   NaN   Delhi  55000.0

In [23]:
df.sort_values(["City", "Salary"])

      Name   Age    City   Salary
2  Charlie   NaN   Delhi  55000.0
1      Bob  30.0  Mumbai  60000.0
5      Bob  30.0  Mumbai  60000.0
4      Eva  22.0    Pune  45000.0
0    Alice  25.0    Pune  50000.0
3    David  28.0     NaN      NaN

In [24]:
df.isnull().sum()

Name      0
Age       1
City      1
Salary    1
dtype: int64

In [25]:
#df.dropna()

In [26]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [27]:
df

      Name   Age    City   Salary
0    Alice  25.0    Pune  50000.0
1      Bob  30.0  Mumbai  60000.0
2  Charlie  27.0   Delhi  55000.0
3    David  28.0     NaN      NaN
4      Eva  22.0    Pune  45000.0
5      Bob  30.0  Mumbai  60000.0

In [28]:
df["City"] = df["City"].fillna("Not Available")

In [29]:
df

      Name   Age           City   Salary
0    Alice  25.0           Pune  50000.0
1      Bob  30.0         Mumbai  60000.0
2  Charlie  27.0          Delhi  55000.0
3    David  28.0  Not Available      NaN
4      Eva  22.0           Pune  45000.0
5      Bob  30.0         Mumbai  60000.0

In [30]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [31]:
df.duplicated().sum()

np.int64(1)

In [32]:
df.drop_duplicates()

      Name   Age           City   Salary
0    Alice  25.0           Pune  50000.0
1      Bob  30.0         Mumbai  60000.0
2  Charlie  27.0          Delhi  55000.0
3    David  28.0  Not Available      NaN
4      Eva  22.0           Pune  45000.0

In [33]:
#remove duplicates by name

In [34]:
df.drop_duplicates(subset="Name")

      Name   Age           City   Salary
0    Alice  25.0           Pune  50000.0
1      Bob  30.0         Mumbai  60000.0
2  Charlie  27.0          Delhi  55000.0
3    David  28.0  Not Available      NaN
4      Eva  22.0           Pune  45000.0

In [35]:
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

In [36]:
df

      Name   Age           City   Salary
0    Alice  25.0           Pune  50000.0
1      Bob  30.0         Mumbai  60000.0
2  Charlie  27.0          Delhi  55000.0
3    David  28.0  Not Available  55000.0
4      Eva  22.0           Pune  45000.0
5      Bob  30.0         Mumbai  60000.0

In [37]:
#data trasformation

In [38]:
df["Tax"] = df["Salary"] * 0.05

In [39]:
df

      Name   Age           City   Salary     Tax
0    Alice  25.0           Pune  50000.0  2500.0
1      Bob  30.0         Mumbai  60000.0  3000.0
2  Charlie  27.0          Delhi  55000.0  2750.0
3    David  28.0  Not Available  55000.0  2750.0
4      Eva  22.0           Pune  45000.0  2250.0
5      Bob  30.0         Mumbai  60000.0  3000.0

In [40]:
df["City"] = df["City"].str.lower()

In [41]:
df

      Name   Age           City   Salary     Tax
0    Alice  25.0           pune  50000.0  2500.0
1      Bob  30.0         mumbai  60000.0  3000.0
2  Charlie  27.0          delhi  55000.0  2750.0
3    David  28.0  not available  55000.0  2750.0
4      Eva  22.0           pune  45000.0  2250.0
5      Bob  30.0         mumbai  60000.0  3000.0

In [42]:
df["Experience"] = [2, 5, 4, 3, 1, 5]

In [43]:
def salary_category(salary):
    if salary < 50000:
        return "Low"
    elif salary <= 60000:
        return "Medium"
    else:
        return "High"

df["SalaryCategory"] = df["Salary"].apply(salary_category)

In [44]:
df

      Name   Age           City   Salary     Tax  Experience SalaryCategory
0    Alice  25.0           pune  50000.0  2500.0           2         Medium
1      Bob  30.0         mumbai  60000.0  3000.0           5         Medium
2  Charlie  27.0          delhi  55000.0  2750.0           4         Medium
3    David  28.0  not available  55000.0  2750.0           3         Medium
4      Eva  22.0           pune  45000.0  2250.0           1            Low
5      Bob  30.0         mumbai  60000.0  3000.0           5         Medium

In [45]:
df["Name"] = df["Name"].str.upper()

In [46]:
df

      Name   Age           City   Salary     Tax  Experience SalaryCategory
0    ALICE  25.0           pune  50000.0  2500.0           2         Medium
1      BOB  30.0         mumbai  60000.0  3000.0           5         Medium
2  CHARLIE  27.0          delhi  55000.0  2750.0           4         Medium
3    DAVID  28.0  not available  55000.0  2750.0           3         Medium
4      EVA  22.0           pune  45000.0  2250.0           1            Low
5      BOB  30.0         mumbai  60000.0  3000.0           5         Medium

In [ ]:
#df.to_csv("cleaned_employee_data.csv", index=False)